version: "3.7"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=jeanmgirard
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    volumes:
      - postgresql:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - postgresql_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 9010:80
    links:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: jean.m.girard@outlook.com
      PGADMIN_DEFAULT_PASSWORD: admin
volumes:
  postgresql:
  postgresql_data:
