version: "3.7"
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: unless-stopped
#    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['packages_enabled'] = true
        gitlab_rails['packages_storage_path'] = "/mnt/packages"
        gitlab_rails['gitlab_shell_ssh_port'] = 8022
        
#        external_url 'http://localhost:8020'
    ports:
      - '8020:80'
      - '8021:443'
      - '8022:22'
    volumes:
      - 'vol_config:/etc/gitlab'
      - 'vol_logs:/var/log/gitlab'
      - 'vol_data:/var/opt/gitlab'
      - 'vol_packages:/mnt/packages'

volumes:
  vol_packages:
  vol_config:
  vol_logs:
  vol_data:


# docker exec -it gitlab update-permissions